## Image Pre-Processing using PIL

### Load and Display Image

In [1]:
# load and show an image with Pillow
from PIL import Image
# load the image
image = Image.open('Sydney-Opera-House.jpg')
# show the image
image.show()

### Show the Information of Image

In [2]:
# summarize some details about the image
print("Image Format: ",image.format)
print("Pixel Channel Format: ",image.mode)
print("Dimensions of the Image: ",image.size)

Image Format:  JPEG
Pixel Channel Format:  RGB
Dimensions of the Image:  (640, 360)


### Extract Features of Images (Pixels)

In [3]:
import numpy as np

# convert image to numpy array
data = np.asarray(image)
# summarize shape
print(data.shape)
# show data
print(data)

(360, 640, 3)
[[[170 187 203]
  [170 187 203]
  [170 187 203]
  ...
  [141 165 193]
  [141 165 193]
  [141 165 193]]

 [[170 187 203]
  [170 187 203]
  [170 187 203]
  ...
  [141 165 193]
  [141 165 193]
  [141 165 193]]

 [[170 187 203]
  [170 187 203]
  [170 187 203]
  ...
  [141 165 193]
  [141 165 193]
  [141 165 193]]

 ...

 [[ 85  95 104]
  [ 75  85  94]
  [ 81  91 100]
  ...
  [ 64  79 100]
  [ 60  75  96]
  [ 62  77  98]]

 [[ 72  82  91]
  [ 60  70  79]
  [ 51  61  70]
  ...
  [ 61  76  97]
  [ 58  73  94]
  [ 53  68  91]]

 [[ 31  41  51]
  [ 33  43  53]
  [ 29  39  49]
  ...
  [ 55  70  91]
  [ 46  61  84]
  [ 36  51  74]]]


### Convert to Grayscale

In [4]:
# convert the image to grayscale
gs_image = image.convert(mode='L')
# save in jpeg format
gs_image.save('opera_house_grayscale.jpg')
# load the image again and show it
image2 = Image.open('opera_house_grayscale.jpg')
# show the image
image2.show()

In [5]:
# convert image to numpy array
data_gs = np.asarray(gs_image)
# summarize shape
print(data_gs.shape)
# show data
print(data_gs)

(360, 640)
[[183 183 183 ... 161 161 161]
 [183 183 183 ... 161 161 161]
 [183 183 183 ... 161 161 161]
 ...
 [ 93  83  89 ...  76  72  74]
 [ 80  68  59 ...  73  70  66]
 [ 39  41  37 ...  67  59  49]]


### Resize Image

In [6]:
# load the image again
image2 = Image.open('opera_house_grayscale.jpg')
# report the size of the image
print(image2.size)
# create a thumbnail and preserve aspect ratio
# we resize image to (100, 100), which max width=100 and max height=100
image2.thumbnail((100,100))
# report the size of the thumbnail
print(image2.size)
# show the image
image2.show()

(640, 360)
(100, 56)


In [10]:
# load the image again
image2 = Image.open('opera_house_grayscale.jpg')
# report the size of the image
print(image2.size)
# resize image and ignore original aspect ratio
img_resized = image2.resize((200,200))
# report the size of the thumbnail
print(img_resized.size)
# show the image
img_resized.show()

(640, 360)
(200, 200)


### Cropped Image

In [11]:
# load the image again
image2 = Image.open('opera_house_grayscale.jpg')
# create a cropped image
# creates a cropped square image of 100 pixels starting at 100,100 and extending down and left to 200,200
cropped = image2.crop((100, 100, 200, 200))
# show cropped image
cropped.show()

### Image Filtering

In [8]:
from PIL import ImageFilter
# load the image
image = Image.open('Sydney-Opera-House.jpg')
#Image Filtering using Gaussian blur filter
image_filter = image.filter(ImageFilter.GaussianBlur(radius=1))
# show the image
image_filter.show()

In [9]:
from PIL import ImageFilter
# load the image
image = Image.open('Sydney-Opera-House.jpg')
#Image Filtering using Smooth filter
image_filter = image.filter(ImageFilter.SMOOTH)
# show the image
image_filter.show()